trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: build 
  displayName: 'node.js CI'

  jobs:
  - job: buildjob
    displayName: 'build node application'

    steps:
    - checkout: self 
      displayName: 'cloning and checkout the code'

    - task: Usenode@1
      displayName: 'install node.js'
      inputs:
        version: '24.x'

    - script: |
        node --version
        npm --version
      displayName: 'check node and npm'

    - script: |
        npm ci
      displayName: 'install dependencies'

    - script: |
        npm test
      displayName: 'run test'

    - script: |
        npm start &
        sleep 5
        curl -I http://localhost:3000/health
      displayName: 'start and health check'

    
    - task: ArchiveFiles@2
      displayName: 'Create Application Package'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/node-app.zip'
        replaceExistingArchive: true

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/node-app.zip'
        artifact: 'node-app'    

# =========================
# CD
# =========================
- stage: Deploy
  displayName: 'Deploy to Azure App Service'

  dependsOn: Build
  condition: succeeded()

  jobs:
  - job: DeployToAzure
    displayName: 'Deploy Node.js Application'

    steps:

    - task: DownloadPipelineArtifact@2
      displayName: 'Download Artifact'
      inputs:
        buildType: 'current'
        artifactName: 'node-app'
        targetPath: '$(Pipeline.Workspace)/node-app'

    - task: AzureWebApp@1
      displayName: 'Deploy to Azure App Service'
      inputs:
        azureSubscription: 'azure-node-cicd-connection'
        appType: 'webAppLinux'
        appName: 'node-cicd-demo'
        package: '$(Pipeline.Workspace)/node-app/node-app.zip'